/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lista;

import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Abril
 */
public class Helados extends javax.swing.JFrame {

    SimpleDateFormat dat = new SimpleDateFormat("dd-MM-yyyy");
    String nombreTamano = "";
    String nuevotopping = "";
    String fecha = dat.format(new Date());
    double subtot = 0.0;
    double iva = 0.0;
    double total1 = 0.0;

    /**
     * Creates new form Botones
     */
    public Helados() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngTamano = new javax.swing.ButtonGroup();
        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        rbtnSencillo = new javax.swing.JRadioButton();
        rbtnDoble = new javax.swing.JRadioButton();
        rbtnJumbo = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        cbxChispas = new javax.swing.JCheckBox();
        cbxChocolate = new javax.swing.JCheckBox();
        cbxGomitas = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JTextField();
        txtIva = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btnSuma = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        dcFecha = new com.toedter.calendar.JDateChooser();
        btnFecha = new javax.swing.JButton();
        btnMostar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 400));
        setSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 153));
        jPanel7.setMinimumSize(new java.awt.Dimension(600, 400));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)), "TAMAÑO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 153, 204))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btngTamano.add(rbtnSencillo);
        rbtnSencillo.setText("Sencillo $20");
        jPanel1.add(rbtnSencillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 33, -1, -1));

        btngTamano.add(rbtnDoble);
        rbtnDoble.setText("Doble $30");
        rbtnDoble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnDobleActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnDoble, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 74, -1, -1));

        btngTamano.add(rbtnJumbo);
        rbtnJumbo.setText("Jumbo $45");
        jPanel1.add(rbtnJumbo, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 115, -1, -1));

        jPanel7.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 140, 160));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 0)), "TOPPING"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxChispas.setText("Chispas $10");
        jPanel3.add(cbxChispas, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 23, -1, -1));

        cbxChocolate.setText("Chocolate $10");
        jPanel3.add(cbxChocolate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        cbxGomitas.setText("Gomitas $10");
        jPanel3.add(cbxGomitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jPanel7.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 140, 160));

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, null));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("SUBTOTAL");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 22, -1, -1));

        jLabel3.setText("IVA");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 60, -1, -1));

        jLabel4.setText("TOTAL");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 98, -1, -1));

        txtSubtotal.setEditable(false);
        txtSubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubtotalActionPerformed(evt);
            }
        });
        jPanel4.add(txtSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 90, -1));

        txtIva.setEditable(false);
        jPanel4.add(txtIva, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 90, -1));

        txtTotal.setEditable(false);
        jPanel4.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 90, -1));

        jPanel7.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 200, 150));

        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSuma.setText("SUMA");
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });
        jPanel5.add(btnSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 73, -1));

        btnLimpiar.setText("LIMPIAR");
        jPanel5.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        btnCerrar.setText("CERRAR");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel5.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jPanel7.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 320, 60));
        jPanel7.add(dcFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 140, 30));

        btnFecha.setText("Mostar Fecha");
        btnFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFechaActionPerformed(evt);
            }
        });
        jPanel7.add(btnFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 120, -1));

        btnMostar.setText("Ticket");
        btnMostar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostarActionPerformed(evt);
            }
        });
        jPanel7.add(btnMostar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Heladería \"Cerebros Congelados\"");
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, 30));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnDobleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnDobleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnDobleActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed
        // TODO add your handling code here:
        double subtotal = 0.0;
        double total = 0.0;
        double ivaSub = 0.00;
        final double IVA = 0.16;
        if (rbtnSencillo.isSelected()) {
            subtotal = subtotal + 20;
            nombreTamano = rbtnSencillo.getText();
            subtot = subtotal;

        }
        if (rbtnDoble.isSelected()) {
            subtotal = subtotal + 30;
            nombreTamano = rbtnDoble.getText();
            subtot = subtotal;
        }
        if (rbtnJumbo.isSelected()) {
            subtotal = subtotal + 45;
            nombreTamano = rbtnJumbo.getText();
            subtot = subtotal;
        }
        if (cbxChispas.isSelected()) {
            subtotal += 10;
            nuevotopping = cbxChispas.getText();
            subtot = subtotal;
        }
        if (cbxChocolate.isSelected()) {
            subtotal += 10;
            nuevotopping = cbxChocolate.getText();
            subtot = subtotal;
        }
        if (cbxGomitas.isSelected()) {
            subtotal += 10;
            nuevotopping = cbxGomitas.getText();
            subtot = subtotal;
        }
        DecimalFormat dec = new DecimalFormat("#.00");
        dec.format(ivaSub);

        ivaSub = subtotal * IVA;
        iva = ivaSub;
        total = subtotal + ivaSub;
        total1=total;
        txtSubtotal.setText(Double.toString(subtotal));
        txtIva.setText(Double.toString(ivaSub));
        txtTotal.setText(Double.toString(total));


    }//GEN-LAST:event_btnSumaActionPerformed

    private void btnFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFechaActionPerformed

        setVisible(true);
// TODO add your handling code here:
        /* JOptionPane.showMessageDialog(null,
    dt.format(dcFecha.getDate()),
    "Mensaje",
    JOptionPane.INFORMATION_MESSAGE);
         */

    }//GEN-LAST:event_btnFechaActionPerformed

    private void btnMostarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostarActionPerformed
        // TODO add your handling code here:
        Ticket t = new Ticket();
        t.setTamano(nombreTamano);
        t.setTopping(nuevotopping);
        t.setFecha(fecha);
        t.setIva(iva);
        t.setSubtotal(subtot);
        t.setTotal(total1);
        t.setVisible(true);


    }//GEN-LAST:event_btnMostarActionPerformed

    private void txtSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubtotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Helados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Helados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Helados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Helados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Helados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnFecha;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMostar;
    private javax.swing.JButton btnSuma;
    private javax.swing.ButtonGroup btngTamano;
    private javax.swing.JCheckBox cbxChispas;
    private javax.swing.JCheckBox cbxChocolate;
    private javax.swing.JCheckBox cbxGomitas;
    private com.toedter.calendar.JDateChooser dcFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton rbtnDoble;
    private javax.swing.JRadioButton rbtnJumbo;
    private javax.swing.JRadioButton rbtnSencillo;
    private javax.swing.JTextField txtIva;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
